export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImF5c2xhbiIsImVtYWlsIjoiYXlzbGFuQGdtYWlsLmNvbSIsImlhdCI6MTY5NzIxNTgxOCwiZXhwIjoxNjk3ODIwNjE4LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMiJ9.KFnDOG6y-0VSGrO03-5qBMfO7xMzdCV2cahyyp9kYl0';
