export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImF5c2xhbiIsImVtYWlsIjoiYXlzbGFuQGdtYWlsLmNvbSIsImlhdCI6MTY5Njk1MDgxMSwiZXhwIjoxNjk3NTU1NjExLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMiJ9.QAPRov0HzHxOV5lK6Cc3FWZVwgSEeWZQu_ZogbpHKbc';
